
# GET http://localhost:1337/todos
# ##

# POST http://localhost:1337/todo/new 
# Content-Type: application/json

# {
# "text": "Pick upxx boat"
# }
# ##

# DELETE  http://localhost:1337/todo/delete/6452e25af69c769cb1212bd7

# ##
# GET  http://localhost:1337/todo/complete/6452e25af69c769cb1212bd7
PUT http://localhost:1337/service/update/64552097417a7a0605e43ca0
Content-Type: application/json

{
"titre": "dfs"
}
# GET http://localhost:1337/s

# POST http://localhost:1337/todo/yarbi_mat3dbnach
# Content-Type: application/json
 

# {
# "text": "admsxdfindf"
# }
 